version: "3.8"

services:
  # Base de datos centralizada
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: sanos_y_salvos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - sanos-network

  # Microservicio de Usuarios
  usuario-service:
    image: jeankaled/usuario-service:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_sanos_usuarios
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - sanos-network

  # Microservicio de Mascotas
  mascota-service:
    image: jeankaled/mascota-service:latest
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_sanos_mascota
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - sanos-network

  # Microservicio de Notificaciones
  notificacion-service:
    image: jeankaled/notificacion-service:latest
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_sanos_notificaciones
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - sanos-network

  # Microservicio de Datos y Analítica
  datos-analitica-service:
    image: jeankaled/datos-analitica-service:latest
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_sanos_analitica
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
    depends_on:
      - db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - sanos-network

  # Microservicio de Integración Externa
  integracion-externa-service:
    image: jeankaled/integracion-externa-service:latest
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_sanos_integraciones
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
    depends_on:
      - db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - sanos-network

volumes:
  postgres_data:

networks:
  sanos-network:
    driver: overlay
