spring.application.name=mascota-service
# Puerto donde correrá este microservicio
server.port=8081

# Conexión a la base de datos de mascotas
spring.datasource.url=jdbc:postgresql://db:5432/db_sanos_mascotas
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true